### PR TITLE
Tidy up code, fixes #11.

### LINKED ISSUE #11: Incorrect minification of percentage based RGB(a) functions.
These (new) tests are failing:

```
[{
    message: 'should not mangle percentage based rgba values',
    fixture: 'h1{color:rgba(50%,50%,50%,0.5)}',
    expected: 'h1{color:rgba(50%,50%,50%,.5)}'
}, {
    message: 'should convert percentage based rgba values',
    fixture: 'h1{color:rgb(100%,100%,100%)}',
    expected: 'h1{color:#fff}'
}];
```

```
    ✖ should not mangle percentage based rgba values
    -------------------------------------------------
      operator: equal
      expected: |-
        'h1{color:rgba(50%,50%,50%,.5)}'
      actual: |-
        'h1{color:rgba(50,50,50,.5)}'
      at: Test.<anonymous> (~/projects/postcss-colormin/src/__tests__/index.js:101:11)


    ✖ should convert percentage based rgba values
    ----------------------------------------------
      operator: equal
      expected: |-
        'h1{color:#fff}'
      actual: |-
        'h1{color:#646464}'
      at: Test.<anonymous> (~/projects/postcss-colormin/src/__tests__/index.js:101:11)
```

### PR DESCRIPTION
**Pull request by ben-eb**
/cc @TrySound

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -1,61 +1,39 @@
...
-function transform (decl) {
+let transform = decl => {
+    if (/^(?!font|filter|-webkit-tap-highlight-color)/.test(decl.prop)) {
+        decl.value = valueParser(decl.value).walk(function (node) {
+            if (node.type === 'function') {
+                if (/^(rgb|hsl)a?$/.test(node.value)) {
+                    node.value = colormin(stringify(node));
+                    node.type = 'word';
+                }
+                if (node.value === 'calc') {
```
Comment (TrySound) [inline src/index.js]: `else if`

Comment (TrySound) [inline src/index.js]: Or move before

File: src/index.js [hunk 2]
```diff
@@ -1,61 +1,39 @@
...
+};
+
+const plugin = 'postcss-colormin';
 
-export default postcss.plugin('postcss-colormin', () => {
-    return function (css) {
-        css.walkDecls(transform);
-    };
-});
+export default postcss.plugin(plugin, () => css => css.walkDecls(transform));
```
Comment (TrySound) [inline src/index.js]: This seems more readable
```js
export default postcss.plugin('postcss-colormin', () => {
	return css => css.walkDecls(transform);
);
```

File: src/index.js [hunk 3]
```diff
@@ -1,61 +1,39 @@
...
-                }
-            }
-        } else if (node.type === 'word') {
-            node.value = colormin(node.value);
-        }
-    }).toString();
-}
-
-function reduceWhitespaces (decl) {
+let reduceWhitespaces = decl => {
```
Comment (TrySound) [inline src/index.js]: variable doesn't seem better. Arrows are cool, but not in evert case.

File: src/index.js [hunk 4]
```diff
@@ -41,21 +8,31 @@ function reduceWhitespaces (decl) {
             node.before = node.after = '';
         }
     }).toString();
-}
+};
```
Comment (TrySound) [inline src/index.js]: unnecessary semicolon. Add eslint rule

File: src/index.js [hunk 5]
```diff
@@ -41,21 +8,31 @@ function reduceWhitespaces (decl) {
...
     if (decl.prop === '-webkit-tap-highlight-color') {
         if (decl.value === 'inherit' || decl.value === 'transparent') {
             return;
         }
         reduceWhitespaces(decl);
-    } else if (/^(?!font|filter)/.test(decl.prop)) {
-        reduceColor(decl);
     }
-}
+};
```
Comment (TrySound) [inline src/index.js]: semicolon

File: src/index.js [hunk 6]
```diff
@@ -41,21 +8,31 @@ function reduceWhitespaces (decl) {
...
+                node.value = colormin(node.value);
+            }
+        }).toString();
+    }
     if (decl.prop === '-webkit-tap-highlight-color') {
         if (decl.value === 'inherit' || decl.value === 'transparent') {
             return;
         }
         reduceWhitespaces(decl);
-    } else if (/^(?!font|filter)/.test(decl.prop)) {
```
Comment (TrySound) [inline src/index.js]: Let's save this order to reduce comparing?

File: src/index.js [hunk 7]
```diff
@@ -48,14 +15,24 @@ function transform (decl) {
         if (decl.value === 'inherit' || decl.value === 'transparent') {
             return;
         }
-        reduceWhitespaces(decl);
-    } else if (/^(?!font|filter)/.test(decl.prop)) {
-        reduceColor(decl);
+        return reduceWhitespaces(decl);
+    } else if (/^(font|filter)/.test(decl.prop)) {
```
Comment (TrySound) [inline src/index.js]: do not need else in this case
